import { NextFunction, Request, Response } from "express";
import helmet from "helmet";

export const customHelmet = (
  req: Request,
  res: Response,
  next: NextFunction
) => {
  const nonce = res.locals.nonce;

  // Set security headers and require inline scripts to have a nonce generated by the server
  helmet({
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        scriptSrc: ["'self'",`'nonce-${nonce}'`],
      },
    },
  })(req, res, next);

  return next();
};
