import { NextFunction, Request, Response } from "express";
import helmet from "helmet";
import { Logger } from "winston";

export const customHelmet = (
  req: Request,
  res: Response,
  next: NextFunction
) => {
  const logger: Logger = res.locals.logger;
  logger.info(`Setting helmet response headers`);
  try {
  const nonce = res.locals.nonce;

  // Set security headers and require inline scripts to have a nonce generated by the server
  helmet({
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        scriptSrc: ["'self'",`'nonce-${nonce}'`],
      },
    },
    frameguard: {
      action: "deny", // Prevents clickjacking
    }
  })(req, res, next); //helmet is calling next itself

  logger.info(`Helmet response headers set`);
} catch (error) {
  logger.error(`Error setting helmet response headers: ${error}`);
  next(error);
}
};
